steps:
  # Build the Frontend Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY_ID}/${_IMAGE_NAME}:$SHORT_SHA"
      - "-f"
      - "${_SERVICE_PATH}/Dockerfile"
      - "./${_SERVICE_PATH}"

  # Push the image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY_ID}/${_IMAGE_NAME}:$SHORT_SHA"

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: "us-central1"
  _REPOSITORY_ID: "smart-corporate-search"
  _IMAGE_NAME: "frontend"
  _SERVICE_PATH: "frontend"
